#!/bin/bash
set -e

sudo /sbin/set_hostname_color.sh

sudo touch /var/log/oar.log
sudo touch /var/log/auth.log
sudo touch /var/log/supervisor/colmet-server.log

sudo /sbin/rtail /var/log/auth.log /var/log/oar.log /var/log/supervisor/colmet-server.log
