#!/bin/bash
set -e

source <(cat /etc/container_environment.sh | grep "COLOR")

touch /var/log/oar.log
touch /var/log/auth.log
touch /var/log/supervisor/colmet-server.log

/sbin/rtail /var/log/auth.log /var/log/oar.log /var/log/supervisor/colmet-server.log
