#!/bin/bash
set -e

if [ -n "$COW_VOLUMES" ]; then
    echo "Mounting COW volumes..."
    while read cow_volume; do
        # COW_PATH => the final mountpoint
        # RO_PATH => the read only docker mount
        # RW_PATH => contained only local changes layer
        IFS=':' read COW_PATH RO_PATH <<< "$cow_volume"
        mkdir -p "$COW_PATH"
        RW_PATH=$(mktemp -d --tmpdir oardocker_mout.XXXXXXXX)
        unionfs-fuse -o cow -o allow_other,default_permissions,use_ino,suid,dev,nonempty "$RW_PATH"=RW:"$RO_PATH"=RO "$COW_PATH"
        chmod --reference="$RO_PATH" "$COW_PATH"
        chown --reference="$RO_PATH" "$COW_PATH"
        echo " -> $COW_PATH "
    done < <(echo $COW_VOLUMES)
fi

exec python /usr/local/sbin/run_startup_scripts /usr/local/sbin/rtail $(echo $(cat /var/lib/container/log2watch.txt))
