#!/bin/bash
set -e

if [[ ! -e  /etc/ssh/ssh_host_rsa_key ]]; then
    echo "No SSH host key available. Generating one..."
    /usr/bin/ssh-keygen -A
fi

mkdir -p /var/run/sshd

exec /usr/sbin/sshd -D
