#!/bin/bash

. /etc/default/nfs-kernel-server
. /etc/default/nfs-common

stop() {
    service nfs-kernel-server stop
    kill $(pidof rpcbind)
    rm -f /nfs_started
}

start() {
    rpcbind
    service nfs-kernel-server start
    touch /nfs_started
}

start

trap "{ stop; kill 0; }" EXIT

tail -f /dev/null
