#!/bin/bash

  # Cigri pull
  cd /root
  git clone https://github.com/oar-team/cigri.git

  # Cigri install
  cd /root/cigri
  make install-cigri 
  make install-autogenerated-cert

  # Apache configuration (api activation)
  ln -s /etc/cigri/api-apache.conf /etc/apache2/conf-available/cigri-api.conf
  a2enconf cigri-api

  # Cigri config file customization
  perl -pi -e 's/^DATABASE_HOST.*=.*/DATABASE_HOST = "server"/' /etc/cigri/cigri.conf

  # Cigri clusters configuration
  ./sbin/new_cluster.rb tchernobyl https://frontend/oarapi-secured/ cert oardocker oardocker '' tchernobyl oar2_5 core 100 "cluster='tchernobyl'"
  ./sbin/new_cluster.rb threemile https://frontend/oarapi-secured/ cert oardocker oardocker '' threemile oar2_5 core 10 "cluster='threemile'"
  ./sbin/new_cluster.rb fukushima https://frontend/oarapi-secured/ cert oardocker oardocker '' fukushima oar2_5 core 50 "cluster='fukushima'"

  # OAR customisation
  oarnodesetting -p cluster=threemile --sql "network_address='node1'"
  oarnodesetting -p cluster=threemile --sql "network_address='node2'"
  oarnodesetting -p cluster=threemile --sql "network_address='node3'"

  # OARAPI for CIGRI
  cp tools/oardocker/oar-restful-api-secured.conf /etc/apache2/conf-available
  a2enconf oar-restful-api-secured
  a2enmod ssl
  a2ensite default-ssl
  service apache2 restart

