#!/bin/bash
set -e

test ! -f /etc/hostname.color || source /etc/hostname.color

mkdir -p /var/log/supervisor

touch /var/log/auth.log
touch /var/log/supervisor/oar-node.log
touch /var/log/auth.log

usr/local/sbin/rtail /var/log/auth.log /var/log/supervisor/oar-node.log /var/log/auth.log
