#!/bin/bash
set -e

source <(cat /etc/container_environment.sh | grep "COLOR")

mkdir -p /var/log/apache2/
touch /var/log/apache2/access.log
touch /var/log/apache2/error.log
touch /var/log/auth.log

/sbin/rtail /var/log/apache2/access.log /var/log/apache2/error.log /var/log/auth.log

