#!/bin/bash
set -e

echo_and_run() { echo "$@" ; "$@" ; }

stop() {
    service oar-server stop
}

start() {
    service oar-server start
    core=0
    for i in `seq 1 $NUM_NODES`; do
      hostname="node${i}"
      echo_and_run oarnodesetting -a -h $hostname -p cpu=$(expr $i - 1) -p core="$(expr $core + 0)" -p cpuset=0
      echo_and_run oarnodesetting -a -h $hostname -p cpu=$i -p core="$(expr $core + 1)" -p cpuset=0
      core=$(expr $core + 2)
    done
}

start

trap "{ stop; kill 0; }" EXIT

tail -f /var/log/oar.log
