#!/bin/bash
set -e

echo_and_run() { echo "$@" ; "$@" ; }

stop() {
    service oar-server stop
}

start() {
    service oar-server start
}

start

trap "{ stop; kill 0; }" EXIT

tail -f /var/log/oar.log
